defaults:
  - training: default
  - representation: synthetic
  - model: synthetic

hydra:
  run:
    dir: "output/${representation.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}"
  job:
    chdir: True

training:
  wandb_project_name: $IWO_${representation.name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  num_epochs: 300
  lr: 0.01
  debug: False
  optimizer: AdamW
  log_iwo: True
  accelerator: cpu

representation:
  L: 10
  function: "trig"

model:
  default:
    w_sizes: 5,4,3,2,1 # rows of ws # 70,50,20,
    num_hidden_layers: 5,5,4,3,3,3 # first NN-head acts on the representation directly. Should ideally have same or similar capacity as the second NN head acting on the first projection. # 5,5,5,
    hidden_dim: 25,25,20,20,20,20 # 25,25,25,
