wandb_project_name: ???
num_epochs: 100
debug: False
batch_size: 128
num_workers: 3
lr: 0.0008
lr_step_size: 50
lr_gamma: 0.1
optimizer: Adam
accelerator: gpu
es_patience: 4
log_iwo: True
wandb_offline: False
